### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by CaptainNemo66** [alexlance/sms-mms-import-to-signal#10]
I believe there could be an issue with reading in the .xml life. I tried a few different ways and got the error below:

```
<USER>@<MACHINE?:~/<PATH>$ python3 sms-mms-import-to-signal.py --input sms-20231206<TIME>.xml --output bits/ -m -v

Traceback (most recent call last):

  File "<PATH>/signal-sms-mms-importer/sms-mms-import-to-signal.py", line 124, in <module>

    contacts_by_number = get_contacts(cursor)

  File "<PATH>/signal-sms-mms-importer/sms-mms-import-to-signal.py", line 40, in get_contacts

    cursor.execute("select _id, phone, system_display_name from recipient")

sqlite3.OperationalError: no such column: phone

``` 
I included the log file but see no issues. I believe the script just skipped everything and continued on, but I do have multiple files posted in bits/. Any support would be greatly appreciated. I'm going to continue to import and see if it really did skip everything.

[signalsmsmmsimport.log](https://github.com/alexlance/signal-sms-mms-importer/files/13579360/signalsmsmmsimport.log)

**Comment by CaptainNemo66** [comment]
I imported the new backup file and it's just the same contents as the orginal backup so I imagine the new file did not compile correctly.
