### ISSUE TITLE
"sqlite3.OperationalError: no such column" on Windows 11

### ISSUE THREAD

**Issue by barelyevening** [alexlance/sms-mms-import-to-signal#7]
Hey Alex, I followed all the directions to the letter (with the exception of appending "_win" to signalbackup-tools because that's how it downloaded) but I keep getting this error when I try to execute "python3 sms-mms-import-to-signal.py sms-XXXXXXXXXXXXXX.xml bits".

The messages read:
line 258, in <module> thread_id = get_or_make_thread(cursor, r)
and
"line 98, in get_or_make_thread cursor.execute(f"select _id from thread where thread recipient_id = '{r['address']}'")

I know next to nothing about coding (I found this page through Google and created an account to leave this reply), but any advice you can offer would be really appreciated!

**Comment by alexlance** [comment]
I'm not familiar with that problem, but it sounds like the schema (layout) of the database table named `thread` has changed such that it no longer has a particular field on it.

Could you please copy-paste the whole error message, eg when a python program crashes it'll generate lots of output

**Comment by barelyevening** [comment]
when I run python3 sms-mms-import-to-signal.py sms-XXXXXXXXXXXXXX.xml bits I get:

Traceback (most recent call last):
File "C:\Users\USERNAME\downloads\sms-mms-import-to-signal.py", line 258, in <module>
    thread_id = get_or_make_thread(cursor, r)
  File "C:\Users\USERNAME\downloads\sms-mms-import-to-signal.py", line 98, in get_or_make_thread
    cursor.execute(f"select _id from thread where thread_recipient_id = '{r['address']}'")
sqlite3.OperationalError: no such column: thread_recipient_id

when I run python3 sms-mms-import-to-signal.py --input sms-20220611130220.xml --output bits -m -v I get:

Traceback (most recent call last):
  File "C:\Users\USERNAME\downloads\sms-mms-import-to-signal.py", line 226, in <module>
    cursor.execute(f"select _id as mms_id from mms where address = {add} and date = {r['date']}")
sqlite3.OperationalError: no such column: address

Could there be an issue with RCS maybe? Should I be running the script in PowerShell instead of CMD?

**Comment by alexlance** [comment]
So if you peek in the Makefile it indicates that you should first run a command like this:

```signalbackup-tools signal-2022-01-01-01-01-01.backup 123456789101112131415161718192 --output bits/```

Where you would replace the backup file name and the 30 digit key with your own filename and key.

Did you run that first command - were there errors in the output?

**Comment by barelyevening** [comment]
Yes, I did. And no, there were no errors. I have a "bits" folder with over 7,000 files (.bin and .sbf, with a single sqlite database file)

**Comment by alexlance** [comment]
Ok great, if you login to your database and view the table table schema does it look like it has a the right columns fields? Run these:

`cd bits/`
`sqlite3 database.sqlite`   (or whatever the filename of the database file is called)

you should be greeted with an sqlite prompt, one can then inspect eg the `mms` table by running:

`.schema mms`

It'll list out all the columns (fields) on that table. If you paste that output here I can help more.

While you're logged in maybe also run:

`.schema thread` and paste that too.

Also could you go into Signal and tell me the exact version of Signal that you're using 👍

**Comment by barelyevening** [comment]
I just get the error: 

sqlite3 : The term 'sqlite3' is not recognized as the name of a cmdlet, function, script file, or operable program.

Sorry I don't know much about programming. Is this something I need to install?

Also worth mentioning that there's a text file here that I'm not sure was there before. It's called signalsmsmmsimport. And I don't currently have Signal installed but the backup I have was from the latest version (6.6.3)

**Comment by alexlance** [comment]
Ah ok - sounds like one would need to install sqlite3 - if that's ok with you, then something like this should get it installed on windows:

https://www.tutorialspoint.com/sqlite/sqlite_installation.htm

**Comment by barelyevening** [comment]
alright took some doing but here you go

sqlite> .schema mms
CREATE TABLE IF NOT EXISTS "mms" (
  _id INTEGER PRIMARY KEY AUTOINCREMENT,
  date_sent INTEGER NOT NULL,
  date_received INTEGER NOT NULL,
  date_server INTEGER DEFAULT -1,
  thread_id INTEGER NOT NULL REFERENCES thread (_id) ON DELETE CASCADE,
  recipient_id INTEGER NOT NULL REFERENCES recipient (_id) ON DELETE CASCADE,
  recipient_device_id INTEGER,
  type INTEGER NOT NULL,
  body TEXT,
  read INTEGER DEFAULT 0,
  ct_l TEXT,
  exp INTEGER,
  m_type INTEGER,
  m_size INTEGER,
  st INTEGER,
  tr_id TEXT,
  subscription_id INTEGER DEFAULT -1,
  receipt_timestamp INTEGER DEFAULT -1,
  delivery_receipt_count INTEGER DEFAULT 0,
  read_receipt_count INTEGER DEFAULT 0,
  viewed_receipt_count INTEGER DEFAULT 0,
  mismatched_identities TEXT DEFAULT NULL,
  network_failures TEXT DEFAULT NULL,
  expires_in INTEGER DEFAULT 0,
  expire_started INTEGER DEFAULT 0,
  notified INTEGER DEFAULT 0,
  quote_id INTEGER DEFAULT 0,
  quote_author INTEGER DEFAULT 0,
  quote_body TEXT DEFAULT NULL,
  quote_missing INTEGER DEFAULT 0,
  quote_mentions BLOB DEFAULT NULL,
  quote_type INTEGER DEFAULT 0,
  shared_contacts TEXT DEFAULT NULL,
  unidentified INTEGER DEFAULT 0,
  link_previews TEXT DEFAULT NULL,
  view_once INTEGER DEFAULT 0,
  reactions_unread INTEGER DEFAULT 0,
  reactions_last_seen INTEGER DEFAULT -1,
  remote_deleted INTEGER DEFAULT 0,
  mentions_self INTEGER DEFAULT 0,
  notified_timestamp INTEGER DEFAULT 0,
  server_guid TEXT DEFAULT NULL,
  message_ranges BLOB DEFAULT NULL,
  story_type INTEGER DEFAULT 0,
  parent_story_id INTEGER DEFAULT 0,
  export_state BLOB DEFAULT NULL,
  exported INTEGER DEFAULT 0
);
CREATE INDEX mms_read_and_notified_and_thread_id_index ON mms(read, notified, thread_id);
CREATE INDEX mms_type_index ON mms (type);
CREATE INDEX mms_date_sent_index ON mms (date_sent, recipient_id, thread_id);
CREATE INDEX mms_date_server_index ON mms (date_server);
CREATE INDEX mms_thread_date_index ON mms (thread_id, date_received);
CREATE INDEX mms_reactions_unread_index ON mms (reactions_unread);
CREATE INDEX mms_story_type_index ON mms (story_type);
CREATE INDEX mms_parent_story_id_index ON mms (parent_story_id);
CREATE INDEX mms_thread_story_parent_story_index ON mms (thread_id, date_received, story_type, parent_story_id);
CREATE INDEX mms_quote_id_quote_author_index ON mms (quote_id, quote_author);
CREATE INDEX mms_exported_index ON mms (exported);
CREATE INDEX mms_id_type_payment_transactions_index ON mms (_id, type) WHERE type & 12884901888 != 0;
CREATE TRIGGER mms_ai AFTER INSERT ON mms BEGIN INSERT INTO mms_fts(rowid, body, thread_id) VALUES (new._id, new.body, new.thread_id); END;
CREATE TRIGGER mms_ad AFTER DELETE ON mms BEGIN INSERT INTO mms_fts(mms_fts, rowid, body, thread_id) VALUES('delete', old._id, old.body, old.thread_id); END;
CREATE TRIGGER mms_au AFTER UPDATE ON mms BEGIN INSERT INTO mms_fts(mms_fts, rowid, body, thread_id) VALUES('delete', old._id, old.body, old.thread_id); INSERT INTO mms_fts(rowid, body, thread_id) VALUES (new._id, new.body, new.thread_id); END;
CREATE TRIGGER msl_mms_delete AFTER DELETE ON mms BEGIN DELETE FROM msl_payload WHERE _id IN (SELECT payload_id FROM msl_message WHERE message_id = old._id AND is_mms = 1); END;
CREATE TRIGGER reactions_mms_delete AFTER DELETE ON mms
        BEGIN
                DELETE FROM reaction WHERE message_id = old._id AND is_mms = 1;
        END;

sqlite> .schema thread
CREATE TABLE IF NOT EXISTS "thread" (
  _id INTEGER PRIMARY KEY AUTOINCREMENT,
  date INTEGER DEFAULT 0,
  meaningful_messages INTEGER DEFAULT 0,
  recipient_id INTEGER NOT NULL UNIQUE REFERENCES recipient (_id) ON DELETE CASCADE,
  read INTEGER DEFAULT 1,
  type INTEGER DEFAULT 0,
  error INTEGER DEFAULT 0,
  snippet TEXT,
  snippet_type INTEGER DEFAULT 0,
  snippet_uri TEXT DEFAULT NULL,
  snippet_content_type TEXT DEFAULT NULL,
  snippet_extras TEXT DEFAULT NULL,
  unread_count INTEGER DEFAULT 0,
  archived INTEGER DEFAULT 0,
  status INTEGER DEFAULT 0,
  delivery_receipt_count INTEGER DEFAULT 0,
  read_receipt_count INTEGER DEFAULT 0,
  expires_in INTEGER DEFAULT 0,
  last_seen INTEGER DEFAULT 0,
  has_sent INTEGER DEFAULT 0,
  last_scrolled INTEGER DEFAULT 0,
  pinned INTEGER DEFAULT 0,
  unread_self_mention_count INTEGER DEFAULT 0
);
CREATE INDEX thread_recipient_id_index ON thread (recipient_id);
CREATE INDEX archived_count_index ON thread (archived, meaningful_messages);
CREATE INDEX thread_pinned_index ON thread (pinned);
CREATE INDEX thread_read ON thread (read);

I hope I did this right

**Comment by alexlance** [comment]
Yes brilliant job, thank you. 

Ok I've pushed a feature branch for this 6.6.3 version of signal. Looks like they've made some significant changes to the database schema upstream.

If you run this:

`git checkout -t -b signal-6-6-3 origin/signal-6-6-3`

and then try running the commands again - you should get a version of the code that works with this later version of the Signal database (or at least it works for me on a Signal backup from version 6.5.6). If you get more errors feel free to report them and I'll see what I can do.

**Comment by barelyevening** [comment]
now I get:

PS C:\Users\USERNAME> git checkout -t -b signal-6-6-3 origin/signal-6-6-3.git
fatal: not a git repository (or any of the parent directories): .git

Maybe I installed GIT wrong............

**Comment by alexlance** [comment]
You'll need to be inside the folder where the repo exists. Try this first:
`cd signal-sms-mms-importer`

**Comment by barelyevening** [comment]
Okay almost there! Everything ran well but when I open signal now all of the messages are attributed to me, and when I tap "View details" they say "Via Data (Signal)", as opposed to Via SMS. I checked the SMS Backup app and everything looks fine

**Comment by alexlance** [comment]
Okay I've pushed a couple more patches into this git branch. If you run:

`cd signal-sms-mms-importer`
`git pull origin signal-6-6-3`

You should see a message about it pulling down some new changes.

If you then run the process again the message types should look better.

**Comment by barelyevening** [comment]
Well now all the messages are attributed to the other person D:

They're correctly identified as SMS but they also say "Sending Paused"

There are also messages saying "[contact] is on Signal!" about three times between each text. Not sure if that will go away with time or not

**Comment by alexlance** [comment]
Ah ok sounds like we might be a bit stuck then. 

There's a field in the SMS Backup and Restore XML file named `msg_box` for each MMS.

If that field is set to `2`, then the message `type` is set to `128` otherwise `132`. 

I think 128 means it's a message that you've sent, and 132 means it's a message you've received, but I'm not 100% sure.

You could also try these numbers:  10485783 for sent, and 10485780 for received. These are inbuilt signal identifiers so the messages won't look like SMS/MMS any more - but they might have the sent and received authorship looking more accurate.

You can see the line of code that does this here if you want to modify it yourself:

https://github.com/alexlance/signal-sms-mms-importer/blob/e8c3b6b01fa726ef2f052fdc8814076172e62668/sms-mms-import-to-signal.py#L183

Another approach, if you find an exact MMS message in Signal that didn't work out right, and then paste the entirety of the entry for that message _from the XML file_ into this issue ... then maybe I could see why it's not working, but it might be a bit diminishing returns if it's all looking _mostly_ ok from your side.

**Comment by freispiel** [comment]
The signal-6-6-3 branch ran on Windows 11 without any errors, and I was able to restore my messages from the patched backup file. However, no SMS/MMS messages are showing up in Signal. I can see tables like "sms" and "sms_fts" with seemingly proper content in bits/database.sqlite, so I guess the script per se worked. But somehow, Signal silently dropped the SMS/MMS messages when restoring from backup.

I noticed that I was not asked whether I wanted to use Signal as default app for text messaging when reinstalling it, so I am uncertain whether this is an actual bug or intended behavior (of Signal 6.6.3 under Android 13).

Anybody has got any idea what to do?
